### ISSUE TITLE
Bootstrapping sequence documentation improvement

### ISSUE THREAD

**Issue by spth** [digidotcom/DCRabbit_9#4]
I've read the documentation (https://github.com/digidotcom/DCRabbit_9/commit/4e527a939a54a77e0a0eca342690978b13d1adad) and found it helpful.

A few small suggestions:

* Add references to existing documentation (TN206 and chapter 4 of the Rabbit 2000 designers handbook)
* Use terminology more consistent with existing documentation: "initial loader" instead of "cold loader", "secondary loader" instead of "PILOT bios".
* Regarding "Set RTS, clear DTR (already cleared previously).":  Wasn't RTS also already set previously? Since we have a comment on DTR, there should also be one on RTS.

Philipp

**Comment by spth** [comment]
There is another problem in the bootstrapping documentation:

> * Write "Set Baud Rate" command to increase baud rate to maximum
>   (460800 = 0x00070800): 7e 02 00 00 06 04 00 26 0c 00 08 07 00 b5 4d
> * Read the ACK: 7e 02 00 00 86 00 00 9f 88 78 b0
> * Change baud rate to 460800, RTS and DTR still cleared.

How would a NAK look like? How to handle it?
I actually do see NAK for 460800 on the RCM2200 board (it has a Rabbit 2000 at 22.1 MHz, and the pilot.bin from DC9 decides that it can't handle 460800. However, it will work at 230400).
According to the Rabbit 2000 User manual, a Rabbit 2000 at 20.3 MHz would only be able to handle up to 57600.

**Comment by tomlogic** [comment]
See line 53 for NAK: `Responses start the same way, ORing subtype with 0x80 for ACK and 0x40 for NAK .`

If you get a NAK, try a lower baud rate (230400, then 115200) until you get an ACK (or give up and remain at 57600).

**Comment by tomlogic** [comment]
I believe I addressed your suggestions.  Let me know if there's additional room for improvement.
